name: SQL Check

on:
  pull_request:
    branches:
      - master

jobs:
  call-reusable:
    uses: LykkeBusiness/.github/.github/workflows/sql-check/sql-check.yml@master
    with:
      base_branch: "${{ github.base_ref }}"
      compare_branch: "${{ github.head_ref }}"