name: SQL Policy Check

on:
  pull_request:
    branches:
      - master

jobs:
  sql-policy:
    name: SQL Policy Check Job
    uses: LykkeBusiness/.github/.github/workflows/sql-policy.yml@master
    with:
      base_branch: "${{ github.base_ref }}"
      compare_branch: "${{ github.head_ref }}"